script:
  - echo "Pipeline is running"
  - node --version
  - npm --version
  - |
    AUTH_B64=$(printf "%s:%s" "$ARTIFACTORY_PROD_USER" "$ARTIFACTORY_PROD_PASSWORD" | base64 | tr -d '\n')

    cat > "$HOME/.npmrc" <<EOF
    registry=https://repo.artifactory-dogen.group.echonet/artifactory/api/npm/registry.npmjs.org/
    //repo.artifactory-dogen.group.echonet/artifactory/api/npm/registry.npmjs.org/:_auth=${AUTH_B64}
    always-auth=true
    strict-ssl=false
    EOF

  - npm install
  - node node_modules/apigeelint/cli.js -f json.js -x security-lint-plugins -e EX-CS001,EX-CS002,EX-CS003,EX-CS004,EX-CS005,EX-CS006,EX-CS007,EX-CS008,EX-CS010 -s apiproxies/access-token-control/test-access-token-04-jwt-algo-mixed-errors/ -w apigeelint-results.json -q || true
  - node convert-apigeelint-to-gitlab-sast.js apigeelint-results.json gl-sast-report.json
  - ls -la












artifacts:
  when: always
  reports:
    sast: gl-sast-report.json
  paths:
    - apigeelint-results.json
    - gl-sast-report.json
  expire_in: 1 week