# Internal development pipeline for the ApigeeLint security scanner.
#
# It validates two distinct use cases:
#
# 1. test_npm_package
#    Packages the code from the current branch and installs it in an isolated
#    directory. This detects missing files, broken package metadata and CLI
#    resolution problems before a release is created.
#
# 2. apigeelint_security_sast
#    Comes from the reusable local CI template and validates the scanner through
#    the same interface used by consumer repositories.

include:
  # Shared corporate variables and CI definitions.
  - project: "Production-mutualisee/IPS/IDO/gitlab-cicd/pipelines"
    file: ".gitlab-ci.yml"

  # Reusable scanner job maintained in this repository.
  - local: "/ci/apigeelint-security.yml"

variables:
  # During this repository's own pipeline, the scanner source project is the
  # current project.
  APIGEELINT_SECURITY_PROJECT_PATH: "$CI_PROJECT_PATH"

  # Released scanner version tested by the reusable consumer-style job.
  APIGEELINT_SECURITY_REF: "v0.1.0"

  # Test bundles stored in this repository.
  APIGEE_PROXY_ROOT: "apiproxies"

stages:
  - package
  - test

default:
  # Centrally available Node.js runtime already accepted by shared runners.
  image: "$CI_REGISTRY/node:25.8.1-yarn-v2"

test_npm_package:
  stage: package

  script:
    # Validate the credentials needed to download npm dependencies.
    - |
      set -eu

      : "${ARTIFACTORY_PROD_USER:?ARTIFACTORY_PROD_USER is required}"
      : "${ARTIFACTORY_PROD_PASSWORD:?ARTIFACTORY_PROD_PASSWORD is required}"

    # Configure npm to download dependencies through the internal Artifactory
    # registry without storing a permanent token in the repository.
    - |
      AUTH_B64="$(
        printf '%s:%s' \
          "$ARTIFACTORY_PROD_USER" \
          "$ARTIFACTORY_PROD_PASSWORD" |
        base64 |
        tr -d '\n'
      )"

      cat > "$HOME/.npmrc" <<EOF
      registry=https://repo.artifactory-dogen.group.echonet/artifactory/api/npm/registry.npmjs.org/
      //repo.artifactory-dogen.group.echonet/artifactory/api/npm/registry.npmjs.org/:_auth=${AUTH_B64}
      strict-ssl=false
      EOF

      chmod 600 "$HOME/.npmrc"

    # Install exactly the dependency versions recorded in package-lock.json.
    - npm ci --no-audit --no-fund

    # Build the package tarball from the current branch and capture its generated
    # filename instead of hard-coding the package version.
    - PACKAGE_TARBALL="$(npm pack --silent)"
    - test -s "$PACKAGE_TARBALL"
    - printf '%s\n' "$PACKAGE_TARBALL" > package-tarball-name.txt

    # Create an isolated directory that behaves like an external consumer.
    - mkdir package-consumer
    - cd package-consumer
    - npm init -y

    # Install only the generated package, not the current repository directly.
    - PACKAGE_TARBALL="$(cat ../package-tarball-name.txt)"
    - npm install --no-audit --no-fund "../${PACKAGE_TARBALL}"

    # Verify that npm exposed the public CLI declared in package.json.
    - test -x ./node_modules/.bin/apigeelint-security

    # Run the packaged scanner against this repository's proxy test bundles.
    - ./node_modules/.bin/apigeelint-security scan ../apiproxies

    # Validate the raw and GitLab SAST reports generated by the package.
    - test -s apigeelint-results.json
    - test -s gl-sast-report.json
    - node -e "JSON.parse(require('fs').readFileSync('apigeelint-results.json', 'utf8'))"
    - node -e "JSON.parse(require('fs').readFileSync('gl-sast-report.json', 'utf8'))"

  artifacts:
    # Keep diagnostic outputs even if package installation or scanning fails.
    when: always

    paths:
      - "*.tgz"
      - package-consumer/apigeelint-results.json
      - package-consumer/apigeelint-stderr.log
      - package-consumer/gl-sast-report.json

    expire_in: 1 week